from pathlib import Path

import numpy as np
import typer
import dolfinx
import yaml
from mpi4py import MPI
from dolfinx.io import XDMFFile
import scifem

app = typer.Typer(
    help="CLI for applying boundaries and interfaces to a pre-existing brain mesh."
)

# Global domain IDs for Biot-Stokes
POROUS_ID = 1
FLUID_ID = 2

# Boundary IDs
INTERFACE_ID = 1
PIA_ID = 11
EPENDYMA_ID = 12
SKULL_ID = 2
SPINAL_CANAL_ID = 3
FIXED_STEM_ID = 4
AQUEDUCT_MID_ID = 5

# Original markers from fTetWild mesh
CSF_FTW = 1
PAR_FTW = 2
LV_FTW = 3
V4_FTW = 4
V3_FTW = 5

mm2m = 1e-3


@app.command()
def mark(
    input_mesh: Path = typer.Argument(
        ..., help="Path to the input XDMF mesh (generated by generate_mesh.py)."
    ),
    output_mesh: Path = typer.Option(
        None, "-o", "--output", help="Path to save the fully tagged mesh."
    ),
    configfile: Path = typer.Option(..., help="Path to the mesh config file (yaml)."),
):
    """Generates both unified and separated boundary/interface facet tags for a volumetric mesh."""

    if output_mesh is None:
        output_mesh = input_mesh.with_name(input_mesh.stem + "_marked.xdmf")

    # Read the config file for the clip planes
    with open(configfile) as conf_file:
        mesh_config = yaml.load(conf_file, Loader=yaml.UnsafeLoader)
    config = mesh_config["surface"]
    clip_origin_z = config["clip_origin"]["z"] * mm2m

    print(f"Reading mesh and cell tags from {input_mesh}...")
    with XDMFFile(MPI.COMM_WORLD, input_mesh, "r") as xdmf:
        domain = xdmf.read_mesh(dolfinx.cpp.mesh.GhostMode.none)
        try:
            ct = xdmf.read_meshtags(domain, name="subdomains")
            ct2 = xdmf.read_meshtags(domain, name="subdomains_ftetwild")
        except RuntimeError as e:
            print(
                "Error: Could not find 'subdomains' or 'subdomains_ftetwild' tags in the input mesh."
            )
            raise e

    print("Computing boundaries and interfaces...")
    tdim = domain.topology.dim
    fdim = tdim - 1
    domain.topology.create_connectivity(fdim, tdim)

    num_facets = domain.topology.index_map(fdim).size_local

    # Create two separate arrays for the two tagging schemes
    markers_unified = np.zeros(num_facets, dtype=np.int32)
    markers_split = np.zeros(num_facets, dtype=np.int32)

    def get_external_boundary_facets(cell_tags, subdomain_ids):
        exterior_facets = dolfinx.mesh.exterior_facet_indices(domain.topology)
        target_facets = []
        for sub_id in subdomain_ids:
            cells = cell_tags.indices[cell_tags.values == sub_id]
            incident_facets = dolfinx.mesh.compute_incident_entities(
                domain.topology, cells, tdim, fdim
            )
            target_facets.append(np.intersect1d(incident_facets, exterior_facets))

        if target_facets:
            return np.unique(np.hstack(target_facets))
        return np.array([], dtype=np.int32)

    # Fast vectorized interface finding
    aqueduct_facets = scifem.mesh.find_interface(ct2, [V4_FTW], [V3_FTW])
    csf_outer_facets = get_external_boundary_facets(ct2, [CSF_FTW])
    par_outer_facets = get_external_boundary_facets(ct2, [PAR_FTW])

    # Locate the cut plane on the CSF boundary (Spinal Outlet)
    def is_cut_plane(x):
        return np.isclose(x[2], clip_origin_z, atol=5e-4)

    bottom_facets_geom = dolfinx.mesh.locate_entities_boundary(
        domain, fdim, is_cut_plane
    )

    spinal_outlet_facets = np.intersect1d(csf_outer_facets, bottom_facets_geom)
    skull_facets = np.setdiff1d(csf_outer_facets, spinal_outlet_facets)

    # 1. Calculate Unified Interface
    tissue_csf_facets = scifem.mesh.find_interface(ct, [FLUID_ID], [POROUS_ID])
    markers_unified[tissue_csf_facets] = INTERFACE_ID

    # 2. Calculate Split Interfaces (Pia / Ependyma)
    pia_facets = scifem.mesh.find_interface(ct2, [CSF_FTW], [PAR_FTW])
    ependyma_facets_1 = scifem.mesh.find_interface(ct2, [PAR_FTW], [LV_FTW])
    ependyma_facets_2 = scifem.mesh.find_interface(ct2, [PAR_FTW], [V4_FTW])
    ependyma_facets_3 = scifem.mesh.find_interface(ct2, [PAR_FTW], [V3_FTW])
    ependyma_facets = np.concatenate(
        [ependyma_facets_1, ependyma_facets_2, ependyma_facets_3]
    )

    markers_split[pia_facets] = PIA_ID
    markers_split[ependyma_facets] = EPENDYMA_ID

    # Apply common markers to BOTH schemes
    for markers in [markers_unified, markers_split]:
        markers[aqueduct_facets] = AQUEDUCT_MID_ID
        markers[skull_facets] = SKULL_ID
        markers[spinal_outlet_facets] = SPINAL_CANAL_ID
        markers[par_outer_facets] = FIXED_STEM_ID

    # Create the unified MeshTags
    unified_idx = np.where(markers_unified != 0)[0].astype(np.int32)
    bm_unified = dolfinx.mesh.meshtags(
        domain, fdim, unified_idx, markers_unified[unified_idx]
    )
    bm_unified.name = "boundaries"

    # Create the split MeshTags
    split_idx = np.where(markers_split != 0)[0].astype(np.int32)
    bm_split = dolfinx.mesh.meshtags(domain, fdim, split_idx, markers_split[split_idx])
    bm_split.name = "boundaries_split"

    print(f"Exporting fully tagged mesh to {output_mesh}...")
    output_mesh.parent.mkdir(parents=True, exist_ok=True)
    with XDMFFile(domain.comm, output_mesh, "w") as xdmf:
        xdmf.write_mesh(domain)
        xdmf.write_meshtags(ct, domain.geometry)
        xdmf.write_meshtags(ct2, domain.geometry)
        xdmf.write_meshtags(bm_unified, domain.geometry)
        xdmf.write_meshtags(bm_split, domain.geometry)

    print("Process complete. Generated 'boundaries' and 'boundaries_split' mesh tags.")


if __name__ == "__main__":
    app()
